// 코드 사전 탭: 코드 종류·근음 선택, 전체 운지 목록과 필터
// ---- dictionary
const DR=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],DL={1:'C♯·D♭',6:'F♯·G♭'};
let Q=0,R=0,K=-1,POS='all',RG=-1,DN=0,DO=0,DSG=0,LIM=60;
const qsEl=document.getElementById('qs'),rootsEl=document.getElementById('roots'),barEl=document.getElementById('bar');
function drawQ(){qsEl.innerHTML=QS.map((q,i)=>`<button id="q${i}" aria-pressed="${i===Q}">${q.s||'M'} <span style="font-weight:400">${q.n}</span></button>`).join('');qsEl.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{Q=i;K=-1;LIM=60;drawQ();drawRoots();full()})}
function drawRoots(){rootsEl.innerHTML=DR.map((n,i)=>`<button id="r${i}" aria-pressed="${i===R}">${(DL[i]||n)}${QS[Q].s}</button>`).join('');rootsEl.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{R=i;K=-1;LIM=60;drawRoots();full()})}
function full(){const V=voicings(R,Q),nm=names(DR[R],Q);const n=i=>V.all.filter(v=>v.i===i).length;
document.getElementById('stats').innerHTML=`<span class="stat">${nm[0]} 전체 <b>${V.all.length}</b>개</span>`+[1,2].map(k=>`<span class="stat">${SG[k]} <b>${V.all.filter(v=>v.sg===k).length}</b></span>`).join('')+`<span class="stat">개방현 포함 <b>${V.all.filter(v=>v.op).length}</b></span><span class="stat">개방현 없음 <b>${V.all.filter(v=>!v.op).length}</b></span>`+[6,5,4,3,2].map(n=>`<span class="stat">${n}줄 <b>${V.all.filter(v=>v.n===n).length}</b></span>`).join('');
document.getElementById('famh').textContent=V.nf?nm[0]+' 대표 운지':'';document.getElementById('famh').hidden=!V.nf;
document.getElementById('fam').innerHTML=V.all.slice(0,V.nf).map(v=>card(v,nm,R,true)).join('');
barEl.innerHTML=`<button id="fa" data-k="-1" aria-pressed="${K<0}">전체</button>`+nm.map((x,i)=>`<button id="fk${i}" data-k="${i}" aria-pressed="${K===i}">${x}</button>`).join('')+`<label for="rg">프렛 구간</label><select id="rg">${[-1,...Array.from({length:21},(_,i)=>i)].map(i=>`<option value="${i}"${i===RG?' selected':''}>${i<0?'전체':i+'–'+(i+4)+'프렛'}</option>`).join('')}</select><label for="dn">사용 줄 수</label><select id="dn">${NS.map((x,i)=>`<option value="${i}"${i===DN?' selected':''}>${x}</option>`).join('')}</select><label for="dsg">줄 위치</label><select id="dsg">${SG.map((x,i)=>`<option value="${i}"${i===DSG?' selected':''}>${x}</option>`).join('')}</select><label for="do">개방현</label><select id="do">${OS.map((x,i)=>`<option value="${i}"${i===DO?' selected':''}>${x}</option>`).join('')}</select><span class="meta" id="cnt"></span>`;
barEl.querySelectorAll('button').forEach(b=>b.onclick=()=>{K=+b.dataset.k;LIM=60;barEl.querySelectorAll('button').forEach(o=>o.setAttribute('aria-pressed',o===b));list()});
document.getElementById('rg').onchange=e=>{RG=+e.target.value;LIM=60;list()};document.getElementById('dn').onchange=e=>{DN=+e.target.value;LIM=60;list()};document.getElementById('do').onchange=e=>{DO=+e.target.value;LIM=60;list()};document.getElementById('dsg').onchange=e=>{DSG=+e.target.value;LIM=60;list()};list()}
function list(){const V=voicings(R,Q),nm=names(DR[R],Q);const L=V.all.filter(v=>(K<0||v.i===K)&&(RG<0||fits(v,RG))&&nsOk(v,DN)&&osOk(v,DO)&&sgOk(v,DSG));
const df=v=>(K<0||v.i===K)&&(RG<0||fits(v,RG))&&nsOk(v,DN)&&osOk(v,DO)&&sgOk(v,DSG);const CR=DR.map((n,i)=>[(DL[i]||n)+QS[Q].s,voicings(i,Q).all.filter(v=>(RG<0||fits(v,RG))&&nsOk(v,DN)&&osOk(v,DO)&&sgOk(v,DSG)).length]);
document.getElementById('dcnt').innerHTML=`<table><caption>현재 조건에서 근음별 ${QS[Q].n}(${QS[Q].s||'M'}) 코드의 가능한 운지 개수 (슬래시 코드 포함)</caption><tr>${CR.map(x=>`<th>${x[0]}</th>`).join('')}</tr><tr>${CR.map(x=>`<td class="${x[1]?'':'z'}">${x[1]?`<b>${x[1]}</b>개`:'0개'}</td>`).join('')}</tr></table>`;
document.getElementById('cnt').textContent=L.length+'개';document.getElementById('all').innerHTML=L.slice(0,LIM).map(v=>card(v,nm,R,false)).join('');document.getElementById('more').hidden=L.length<=LIM}
document.getElementById('more').onclick=()=>{LIM+=120;list()};
